Document: usbboot
Title: Debian usbboot Manual
Author: <insert document author here>
Abstract: This manual describes what usbboot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/usbboot/usbboot.sgml.gz

Format: postscript
Files: /usr/share/doc/usbboot/usbboot.ps.gz

Format: text
Files: /usr/share/doc/usbboot/usbboot.text.gz

Format: HTML
Index: /usr/share/doc/usbboot/html/index.html
Files: /usr/share/doc/usbboot/html/*.html
